name: 'Agent Iteration Check'
description: 'Track agent auto-fix iterations via PR comments to prevent infinite loops'

inputs:
  pr_number:
    description: 'PR number'
    required: true
  max_iterations:
    description: 'Maximum allowed iterations before stopping'
    required: false
    default: '5'
  agent_type:
    description: 'Agent type to track (review-fix or failure-fix)'
    required: true
  github_token:
    description: 'GitHub token for API operations'
    required: true

outputs:
  iteration_count:
    description: 'Current iteration count'
    value: ${{ steps.check.outputs.iteration_count }}
  effective_max:
    description: 'Effective max iterations after [CONTINUE] multipliers'
    value: ${{ steps.check.outputs.effective_max }}
  continue_count:
    description: 'Number of [CONTINUE] comments from admins'
    value: ${{ steps.check.outputs.continue_count }}
  is_agent_commit:
    description: 'Whether the last commit was made by an agent'
    value: ${{ steps.check.outputs.is_agent_commit }}
  should_skip:
    description: 'Whether to skip this run'
    value: ${{ steps.check.outputs.should_skip }}
  exceeded_max:
    description: 'Whether max iterations have been exceeded'
    value: ${{ steps.check.outputs.exceeded_max }}

runs:
  using: 'composite'
  steps:
    - name: Check iteration count
      id: check
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ inputs.pr_number }}
        MAX_ITERATIONS: ${{ inputs.max_iterations }}
        AGENT_TYPE: ${{ inputs.agent_type }}
      run: |
        echo "=== Agent Iteration Check ==="
        echo "PR: $PR_NUMBER | Max: $MAX_ITERATIONS | Type: $AGENT_TYPE"

        # Check if last commit is an agent commit
        AGENT_AUTHORS=("AI Review Agent" "AI Pipeline Agent" "AI Agent Bot")
        LAST_COMMIT_AUTHOR=$(git log -1 --format='%an' 2>/dev/null || echo "")

        IS_AGENT_COMMIT="false"
        for author in "${AGENT_AUTHORS[@]}"; do
          if [[ "$LAST_COMMIT_AUTHOR" == "$author" ]]; then
            IS_AGENT_COMMIT="true"
            break
          fi
        done
        echo "is_agent_commit=$IS_AGENT_COMMIT" >> $GITHUB_OUTPUT

        # Use github-agents CLI if available (installed on runner)
        if command -v github-agents &>/dev/null; then
          RESULT=$(github-agents iteration-check \
            --pr "$PR_NUMBER" \
            --agent-type "$AGENT_TYPE" \
            --max-iterations "$MAX_ITERATIONS" \
            --format json 2>/dev/null || echo "")

          if [ -n "$RESULT" ] && echo "$RESULT" | jq -e . >/dev/null 2>&1; then
            echo "iteration_count=$(echo "$RESULT" | jq -r '.iteration_count')" >> $GITHUB_OUTPUT
            echo "effective_max=$(echo "$RESULT" | jq -r '.effective_max')" >> $GITHUB_OUTPUT
            echo "continue_count=$(echo "$RESULT" | jq -r '.continue_count')" >> $GITHUB_OUTPUT
            echo "exceeded_max=$(echo "$RESULT" | jq -r '.exceeded_max')" >> $GITHUB_OUTPUT
            echo "should_skip=$(echo "$RESULT" | jq -r '.should_skip')" >> $GITHUB_OUTPUT
            echo "=== Iteration Check Complete (via CLI) ==="
            exit 0
          fi
        fi

        # Fallback: count agent commit metadata comments on the PR
        echo "Falling back to comment-based iteration counting..."
        ITERATION_COUNT=$(gh api "repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \
          --paginate --jq "[.[] | select(.body | contains(\"agent-metadata:type=${AGENT_TYPE}\"))] | length" \
          2>/dev/null || echo "0")

        # Count [CONTINUE] comments from admins
        CONTINUE_COUNT=$(gh api "repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \
          --paginate --jq '[.[] | select(.body | test("\\[CONTINUE\\]"))] | length' \
          2>/dev/null || echo "0")

        EFFECTIVE_MAX=$(( MAX_ITERATIONS + CONTINUE_COUNT * MAX_ITERATIONS ))
        EXCEEDED_MAX="false"
        SHOULD_SKIP="false"
        if [ "$ITERATION_COUNT" -ge "$EFFECTIVE_MAX" ]; then
          EXCEEDED_MAX="true"
          SHOULD_SKIP="true"
        fi

        echo "iteration_count=$ITERATION_COUNT" >> $GITHUB_OUTPUT
        echo "effective_max=$EFFECTIVE_MAX" >> $GITHUB_OUTPUT
        echo "continue_count=$CONTINUE_COUNT" >> $GITHUB_OUTPUT
        echo "exceeded_max=$EXCEEDED_MAX" >> $GITHUB_OUTPUT
        echo "should_skip=$SHOULD_SKIP" >> $GITHUB_OUTPUT

        # Post comment if max iterations exceeded
        if [ "$EXCEEDED_MAX" = "true" ]; then
          if [ "$AGENT_TYPE" = "review-fix" ]; then
            AGENT_NAME="Review Response Agent"
          else
            AGENT_NAME="Failure Handler Agent"
          fi

          COMMENT_FILE=$(mktemp)
          cat > "$COMMENT_FILE" <<COMMENT_EOF
        ## $AGENT_NAME - Iteration Limit Reached
        <!-- agent-metadata:type=${AGENT_TYPE}:iteration=${ITERATION_COUNT}:limit-reached -->

        The **$AGENT_NAME** has reached the iteration limit (**${ITERATION_COUNT}/${EFFECTIVE_MAX}**).
        Further automated fixes from this agent have been paused.

        **To allow more iterations:**
        - An admin can comment \`[CONTINUE]\` to extend the limit
        - Or address the issues manually
        - Or add the \`no-auto-fix\` label to disable automated fixes
        COMMENT_EOF

          gh pr comment "$PR_NUMBER" --body-file "$COMMENT_FILE" || \
            echo "Warning: Failed to post iteration limit comment"
          rm -f "$COMMENT_FILE"
        fi

        echo "=== Iteration Check Complete ==="
        echo "  Count: $ITERATION_COUNT | Max: $EFFECTIVE_MAX | Exceeded: $EXCEEDED_MAX"
